server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: kiki-register
  security:
    user:
      name: kiki
      password: 123456
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: kiki
        password: 123456

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*' #表示将SBA客户端的所有监控端点都暴露给SBA服务端
  endpoint:
    health:
      show-details: ALWAYS #表示总是展示详细的健康信息

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30  #微服务更新实例信息的变化到Eureka服务端的间隔时间，单位为秒，这里指定为30秒（这就是微服务启动后，要过一会才能注册到Eureka服务端的原因）
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
