server:
  port: 8301


spring:
  application:
    name: kiki-gateway
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
             org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  boot:
    admin:
      client:
        url: http://${kiki-monitor-admin}:8401
        username: kiki
        password: 123456

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*' #表示将SBA客户端的所有监控端点都暴露给SBA服务端
  endpoint:
    health:
      show-details: ALWAYS #表示总是展示详细的健康信息

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 20
    serviceUrl:
      defaultZone: http://kiki:123456@${kiki-register}:8001/register/eureka/

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: kiki-auth
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: kiki-server-system
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: kiki-server-test
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  SendErrorFilter:
    error:
      disable: true  #默认的异常过滤器失效,使用 com.sxdx.kiki.gateway.filter.KikiGatewayErrorFilter 自定义处理类

#解决zuul gateway经常会出现超时
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000